### ISSUE TITLE
Crash by Create Innovations-1.0.0

### ISSUE THREAD

**Issue by Gonbuto** [ShadowFire5650/Create-Innovations#1]
Excuse me.
I would like to report a crash when installing Create Innovations-1.0.0.

Mod:
forge-1.18.2-40.2.0
rubidium-0.5.4
rubidium-extra-0.4.16+mc1.18.2-build.57
jei-1.18.2-forge-10.2.1.1002
Jade-1.18.2-forge-5.2.6
Mantle-1.18.2-1.9.43
TConstruct-1.18.2-3.6.2.92
flywheel-forge-1.18.2-0.6.8.a
create-1.18.2-0.5.0.i
createaddition-1.18.2-20221219a
create_innovations-1.0.0
[crash-2023-01-30_22.00.03-fml.txt](https://github.com/ShadowFire5650/Create-Innovations/files/10536036/crash-2023-01-30_22.00.03-fml.txt)

**Comment by ModestBitboard** [comment]
Sorry about the crash! Try an older version of create such as 0.5.0e and an older version of flywheel.
